language: rust
rust: [stable, beta, nightly]
cache: cargo
before_script:
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]] ; then cargo install clippy --force ; fi'

script:
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]] ; then cargo clippy ; else cargo build ; fi'
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
